# Generated by Django 4.1 on 2022-08-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyitem',
            name='actual',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
